// Loads data/targets.json (generated by AstroTonight/Tools/export_tonight_data.py)
// and derives the same display fields the app computes on DeepSkyObject:
// displayName, typeLabel, and the secondary/common name shown only when it
// adds information. Ported from AstroTonight/Models/DeepSkyObject.swift and
// AstroTonight/Views/ObjectRow.swift.

const TYPE_LABELS = {
  G: "Galaxy",
  GPair: "Galaxy Pair",
  GTrpl: "Galaxy Triplet",
  GGroup: "Group of Galaxies",
  PN: "Planetary Nebula",
  OCl: "Open Cluster",
  GCl: "Globular Cluster",
  "Cl+N": "Cluster + Nebula",
  HII: "HII Region",
  EmN: "Emission Nebula",
  RfN: "Reflection Nebula",
  DrkN: "Dark Nebula",
  SNR: "Supernova Remnant",
  Neb: "Nebula",
  Nova: "Nova",
  "*": "Star",
  "**": "Double Star",
  "*Ass": "Star Association",
  Other: "Other",
};

export function typeLabel(typeCode) {
  return TYPE_LABELS[typeCode] ?? typeCode;
}

/** Port of DeepSkyObject.displayName's 3-branch logic. */
export function displayName(obj) {
  if (obj.messierNumber != null) return `M${obj.messierNumber}`;
  if (obj.caldwellNumber != null && /^C\d+$/.test(obj.name)) {
    // Caldwell numbers are reference/search only, never the primary name.
    if (obj.sharplessNumber != null) return `Sh2-${obj.sharplessNumber}`;
    const first = firstCommonName(obj);
    if (first) return first;
    return obj.name;
  }
  return obj.name;
}

function firstCommonName(obj) {
  if (!obj.commonNames) return null;
  const first = obj.commonNames.split(",")[0].trim();
  return first || null;
}

/** "NGC 1" and "NGC0001" are the same designation formatted differently;
 * port of ObjectRow.swift's isSameDesignation. */
function normalizeDesignation(s) {
  return s.toLowerCase().replace(/ /g, "").replace(/([a-z])0+/g, "$1");
}

/** The common name shown on the row's first line, only when it isn't just
 * a re-spelling of displayName. */
export function secondaryName(obj, resolvedDisplayName) {
  const first = firstCommonName(obj);
  if (first && normalizeDesignation(first) !== normalizeDesignation(resolvedDisplayName)) {
    return first;
  }
  return null;
}

export async function loadTargets() {
  const res = await fetch("data/targets.json");
  if (!res.ok) throw new Error(`Failed to load targets.json: ${res.status}`);
  const raw = await res.json();
  return raw.map((obj) => {
    const name = displayName(obj);
    return {
      ...obj,
      displayName: name,
      typeLabel: typeLabel(obj.typeCode),
      secondaryName: secondaryName(obj, name),
    };
  });
}
